name:           Bootstrap Blog
description:    Official blog for the Bootstrap framework.
url:            http://blog.getbootstrap.com

markdown:       rdiscount
permalink:      pretty
pygments:       true
paginate:       5
encoding:       UTF-8

exclude:        ["README.md"]
